[package]
name = "naxious/syscore"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

description = "A simple 'ModuleScript' loader that allows for easy priority loading, error reporting, and debugging"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
